#-------------------------------
# General Site Settings
title: Xinming Pei's Homepage
# logo: logo.svg # You can add own logo.
# description: Zolan is modern minimal theme for Jekyll


#-------------------------------
# Author Settings
author:
  name: Xinming Pei
  image: 01.jpg
  say-hello: <strong>Xinming Pei</strong> (<strong>裴鑫铭</strong>)
  bio: 'I am a PhD student at the State Key Laboratory of CAD & CG, Zhejiang University, where I am supervised by <strong><a href="http://www.cad.zju.edu.cn/home/weiweixu/" target="_blank">Prof. Weiwei Xu</a></strong> and <strong><a href="https://lanlei.github.io/" target="_blank">Dr. Lei Lan</a></strong>. My research focuses on physics-based modeling and simulation, parallel computing, and their integration with embodied intelligence.'


#-------------------------------
# Contact links
# twitter: https://twitter.com/ # Add your Twitter handle
# facebook: https://facebook.com/ # Add your Facebook handle
# dribbble: https://dribbble.com/ # Add your Dribbble handle
# instagram: https://instagram.com/ # Add your Instagram handle
# pinterest: https://pinterest.com/ # Add your Pinterest handle
github: https://github.com/KevinPei777
email: mailto:xmpei@zju.edu.cn 

#-------------------------------
# Comment Section (Disqus)
disqus-identifier: mr-brown # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: artemsheludko_ # Add instagram username

#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

#-------------------------------
# Navigation (custom order)
nav:
  - title: Home
    url: /
  - title: Publications
    url: /publications/
  - title: Experience
    url: /experience/
  - title: Others
    url: /others/
  - title: Style Guide
    url: /styleguide/
